sudo: false

language: csharp

os:
  - linux

dist: trusty

mono: none

dotnet: 2.1.101

env:
  global:
    - VIPS_VERSION=8.6.3
    - VIPS_TAR_VERSION=$VIPS_VERSION
    # - VIPS_WARNING=0
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

cache:
  directories:
    - tools
    - $HOME/vips

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libglib2.0-dev

before_install:
  - bash install-vips.sh --without-python

script: ./build.sh