sudo: false

language: csharp

mono: none

dotnet: 2.1.402

env:
  global:
    - VIPS_VERSION=8.7.0
    - VIPS_TAR_VERSION=$VIPS_VERSION
    - VIPS_WARNING=0
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - DYLD_LIBRARY_PATH=$HOME/vips/lib:$DYLD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    # these are just to make travis's UI a bit prettier
    - os: linux
      # Ubuntu 14.04
      dist: trusty
      env:
        - JOBS=`nproc`
    - os: osx
      # OS X 10.13
      osx_image: xcode9.4
      env:
        - JOBS="`sysctl -n hw.ncpu`"
        - PATH="/usr/local/opt/ccache/bin:$PATH"
        - HOMEBREW_NO_AUTO_UPDATE=1

cache:
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - tools
    - $HOME/vips

addons:
  apt:
    packages:
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libglib2.0-dev

before_install: ./build/travis.sh

script: ./build.sh